---
- hosts: 192.168.56.131
  become: yes
  become_user: root
  tasks:
    - name: "List the items of created file"
      command: "ls /home/vagrant"
      register: file_name
      
    - name: Set variables
      debug:
        msg: "{{ item }}"
      with_items: "{{ file_name.stdout_lines }}"
            
    - name: some name
      #shell: cat {{ item }}
      set_fact:
        annoying: 
          - "{{ item }}"
      with_items: "{{ file_name.stdout_lines }}"
      
    - name: Show information
      debug:
        var: annoying
      
