---
- hosts: 192.168.56.131
  become: yes
  become_user: root
  tasks:
    - name: "List the items of created file"
      command: "ls /home/vagrant"
      register: file_name
      
    - name: Set variables
      shell: cat {{ items.stdout_lines }}
      register: annoying
      with_items: "{{ file_name.stdout_lines }}"
      
