---
- hosts: 192.168.56.131
  become: yes
  become_user: root
  tasks:
    - name: "List the items of created file"
      command: "ls /home/vagrant"
      register: file_name
      
    - name: Set variables
      set_fact:
        file: "{{ items }}"
      with_items: "{{ file_name.stdout_lines }}"
      register: annoying
      
    - name: print variable
      debug:
        msg: "{{ annoying.stdout_lines }}"
      
