---
- hosts: 192.168.56.131
  become: yes
  become_user: root
  tasks:
    - name: "List the items of created file"
      command: "ls /home/vagrant"
      register: file_name

    - name: Print the file name
      set_fact:
        file: "{{ item }}"
    - debug:
        msg: "{{item}}"
      read: "{{item}}"  
      with_items: "{{ file_name.stdout_lines }}"

    - name: read the file name output
      command: "cat {{ read }}"
      register: op_txt

    - name: print the output
      debug:
        msg: "{{ op_txt.stdout_lines }}"
