--- 
- hosts: 192.168.56.131
  become: yes
  become_user: root
  tasks:
    - name: "Ansible command module multiple commands"
      command: "touch {{ item }}"
      with_items:
        - file1.txt
        - file2.txt
        - file3.txt
      args: 
       chdir: /home/vagrant
      register: file_name

    - name: Print the file name output
      debug:
      msg: "{{ file_name }}"


