--- 
- hosts: localhost
  become: yes
  become_user: root
  tasks:
    - name: "Ansible command module multiple commands"
      command: "touch {{ item }}"
      with_items:
        - file1.txt
        - file2.txt
        - file3.txt
      args: 
       chdir: /home/vagrant
      register: file_name


